class RagError(Exception):
    """Основание иерархии. Ловить его в обработчике запроса допустимо."""

class Degradable(RagError):
    """Отказ, после которого работа продолжается с худшим качеством."""

class Fatal(RagError):
    """Отказ, после которого продолжать бессмысленно."""

class SourceUnavailable(Degradable): ...
class RerankerUnavailable(Degradable): ...
class BudgetExhausted(Degradable): ...

class CorpusUnavailable(Fatal): ...
class ModelUnavailable(Fatal): ...
