class RagError(Exception):
    """The hierarchy's root. Catching it in a request handler is legitimate."""

class Degradable(RagError):
    """A failure after which work continues at reduced quality."""

class Fatal(RagError):
    """A failure after which continuing is pointless."""

class SourceUnavailable(Degradable): ...
class RerankerUnavailable(Degradable): ...
class BudgetExhausted(Degradable): ...

class CorpusUnavailable(Fatal): ...
class ModelUnavailable(Fatal): ...
